name: build dapp

on: [push]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: pnpm build

  deploy:
    name: GitHub Pages
    runs-on: ubuntu-latest
    needs: [install]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Deploy: ({sha}) {msg}'
